### ISSUE TITLE
Geotif raster not visible in offline

### ISSUE THREAD

**Issue by badshah424** [taylorhixson/WF#4]
Hi I am using a geotif image in QGIS and trying converting it to offline with QGIS2WEB plugin .

But nowhere I'm getting options for Raster map and as a result my web map is not having the geotif file anywhere .

Basically I want to create a offline map with layers. One of the layers being Raster of geotif.

Please help.

**Comment by taylorhixson** [comment]
Hi! You need to turn a raster into a tile layer first for it to work in Leaflet. I am not very experienced in using QGIS plugins to create tile layers, and qgis2web does not have this function, as far as I'm aware. If you want to make this offline, I won't be able to provide help. My experience with Leaflet maps is primarily for interactive maps that will be published online.

If you are able to support your map with online use/access, the easiest way I have supported rasters in my web maps is to use a web service to host the raster. For a free service, I use [mapwarper.net](https://mapwarper.net/). Using MapWarper requires you to have rights to share the map, and you will have to georeference the map again when uploading it.

Then, you need to create a new variable in the exported qgis2web Leaflet code in the same way the basemap is added ([See lines 84-87](https://github.com/taylorhixson/WF/blob/master/webapp/index.html)). If using MapWarper, replace the OSM link with the Tiles link (e.g., change 'http://tile.openstreetmap.org/{z}/{x}/{y}.png' to  'https://mapwarper.net/maps/tile/34234/{z}/{x}/{y}.png'). You should update or remove the attribution as needed, and optionally, change opacity.

Hope this helps!
